services:
  db:
    image: pgvector/pgvector:pg17
    container_name: elizaos-postgres
    environment:
      POSTGRES_USER: elizauser
      POSTGRES_PASSWORD: password
      POSTGRES_DB: elizaos
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
