[profile.default]
src = "src"
out = "out"
libs = ["lib", 'node_modules']
remappings = [
    "forge-std/=lib/forge-std/src/"
]
solc_version = "0.8.28"
optimizer = true
optimizer_runs = 200
via_ir = true

[rpc_endpoints]
fuji = "https://api.avax-test.network/ext/bc/C/rpc"
sepolia = "https://sepolia.infura.io/v3/e909ef7e3aaa4a2cbb627fbee4ffd000"

[etherscan]
fuji = { key = "${SNOWTRACE_API_KEY}", url = "https://api.snowtrace.io/api" }
sepolia = { key = "${ETHERSCAN_API_KEY}", url = "https://api-sepolia.etherscan.io/api" }