[profile.default]
src = "src"
out = "out"
libs = ["node_modules", "lib"]
remappings = [
  "forge-std/=lib/forge-std/src/"
]

[rpc_endpoints]
fuji = "https://api.avax-test.network/ext/bc/C/rpc"
